insert into contas (empresa_id, tipo, codigo, nome) values
(2, 'despesa', 1, 'pasto'),
(2, 'investimento', 101, 'compra de bezerros'),
(2, 'receita', 201, 'venda de garrotes'),
(2, 'despesa', 2, 'vaqueiro'),
(2, 'receita', 202, 'venda de bois'),
(2, 'despesa', 3, 'sal'),
(2, 'receita', 203, 'emprestimo recebido'),
(2, 'despesa', 4, 'medicamentos / vacinas'),
(2, 'receita', 204, 'outros'),
(2, 'despesa', 5, 'combustivel'),
(2, 'receita', 205, 'LIMABANK recebido/resgatado'),
(2, 'despesa', 6, 'manutencao / transporte'),
(2, 'despesa', 7, 'impostos'),
(2, 'despesa', 8, 'gerente/secretária'),
(2, 'despesa', 9, 'administracao'),
(2, 'despesa', 10, 'banco'),
(2, 'despesa', 11, 'tropa'),
(2, 'despesa', 12, 'despesas sede'),
(2, 'despesa', 13, 'reprodução'),
(2, 'despesa', 14, 'outros'),
(2, 'despesa', 15, 'cartório/documentação'),
(2, 'despesa', 16, 'frete gado entre fazendas'),
(2, 'despesa', 17, 'comissão funcionários'),
(2, 'despesa', 18, 'diárias confinamento'),
(2, 'despesa', 19, 'itens de manejo'),
(3, 'despesa', 1, 'pasto'),
(3, 'investimento', 101, 'Compra bezerras'),
(3, 'receita', 201, 'Venda bezerros'),
(3, 'despesa', 2, 'vaqueiro'),
(3, 'receita', 202, 'Venda vacas'),
(3, 'despesa', 3, 'sal'),
(3, 'receita', 203, 'LIMABANK recebido/resgatado'),
(3, 'despesa', 4, 'ração'),
(3, 'receita', 204, 'empréstimo recebido'),
(3, 'despesa', 5, 'medicamentos/vacinas'),
(3, 'despesa', 6, 'reprodução'),
(3, 'despesa', 7, 'impostos'),
(3, 'despesa', 8, 'veterinário'),
(3, 'despesa', 9, 'administracao'),
(3, 'despesa', 10, 'banco'),
(3, 'despesa', 11, 'outros'),
(3, 'despesa', 12, 'comissão funcionários'),
(3, 'despesa', 13, 'frete entre fazendas'),
(3, 'despesa', 14, 'diárias confinamento'),
(4, 'despesa', 1, 'irrigação adubo'),
(4, 'investimento', 101, 'estrutura'),
(4, 'receita', 201, 'recebimento diarias top boi'),
(4, 'despesa', 2, 'irrigação mão de obra'),
(4, 'receita', 202, 'recebimento diarias top vacas'),
(4, 'despesa', 3, 'irrigação máquinas'),
(4, 'receita', 203, 'recebimento diarias outros'),
(4, 'despesa', 4, 'irrigação defensivos'),
(4, 'receita', 204, 'LIMABANK recebido/resgatado'),
(4, 'despesa', 5, 'irrigacao manutencao'),
(4, 'despesa', 6, 'irrigação sementes/mudas'),
(4, 'despesa', 7, 'adm'),
(4, 'despesa', 8, 'confinamento mao obra'),
(4, 'despesa', 9, 'confinamento maquinas'),
(4, 'despesa', 10, 'cofinamento suplementacao'),
(4, 'despesa', 11, 'confinamento manutenção'),
(4, 'despesa', 12, 'silagem'),
(4, 'despesa', 13, 'banco'),
(5, 'despesa', 1, 'funcionário trator A750'),
(5, 'investimento', 101, 'compra de máquina'),
(5, 'receita', 201, 'horas trator TERRAS'),
(5, 'despesa', 2, 'horas trator A750'),
(5, 'receita', 202, 'horas carregadeira TERRAS'),
(5, 'despesa', 3, 'combustível trator A750'),
(5, 'receita', 203, 'horas máquinas OUTROS'),
(5, 'despesa', 4, 'peças trator A750'),
(5, 'receita', 204, 'horas máquinas OUTROS'),
(5, 'despesa', 5, 'serviços trator A750'),
(5, 'receita', 205, 'LIMABANK recebido/resgatado'),
(5, 'despesa', 6, 'funcionário trator A800'),
(5, 'despesa', 7, 'horas trator A800'),
(5, 'despesa', 8, 'combustível trator A800'),
(5, 'despesa', 9, 'peças trator A800'),
(5, 'despesa', 10, 'serviços trator A800'),
(5, 'despesa', 11, 'funcionário trator A990'),
(5, 'despesa', 12, 'horas trator A990'),
(5, 'despesa', 13, 'combustível trator A990'),
(5, 'despesa', 14, 'peças trator A990'),
(5, 'despesa', 15, 'serviços trator A990'),
(5, 'despesa', 16, 'funcionário carregadeira'),
(5, 'despesa', 17, 'horas carregadeira'),
(5, 'despesa', 18, 'combustível carregadeira'),
(5, 'despesa', 19, 'peças carregadeira'),
(5, 'despesa', 20, 'serviços carregadeira'),
(5, 'despesa', 21, 'adm'),
(5, 'despesa', 22, 'veículo/transporte'),
(5, 'despesa', 23, 'banco'),
(5, 'despesa', 24, 'grade'),
(5, 'despesa', 25, 'roçadeira'),
(5, 'despesa', 26, 'outros implementos/ferramentas'),
(5, 'despesa', 27, 'erro'),
(6, 'despesa', 1, 'núcleo mineral'),
(6, 'investimento', 101, 'máquinas'),
(6, 'receita', 201, 'vendas TOP BOI'),
(6, 'despesa', 2, 'sal branco'),
(6, 'receita', 202, 'vendas TOP VACAS'),
(6, 'despesa', 3, 'ureia'),
(6, 'receita', 203, 'vendas outros'),
(6, 'despesa', 4, 'calcário'),
(6, 'receita', 204, 'rendimento banco'),
(6, 'despesa', 5, 'fubá'),
(6, 'receita', 205, 'LIMABANK recebido/resgatado'),
(6, 'despesa', 6, 'soja'),
(6, 'despesa', 7, 'ddg'),
(6, 'despesa', 8, 'caroço de algodão'),
(6, 'despesa', 9, 'mão de obra'),
(6, 'despesa', 10, 'carregamento'),
(6, 'despesa', 11, 'adm'),
(6, 'despesa', 12, 'manutenção'),
(6, 'despesa', 13, 'tarifas bb'),
(6, 'despesa', 14, 'Outros'),
(6, 'despesa', 15, 'ERRO'),
(7, 'despesa', 1, 'Motorista'),
(7, 'investimento', 101, 'compra caminhão'),
(7, 'receita', 201, 'agropecuária pontual'),
(7, 'despesa', 2, 'Abastecimento'),
(7, 'receita', 202, 'agro lima'),
(7, 'despesa', 3, 'Manutenção'),
(7, 'receita', 203, 'outros clientes'),
(7, 'despesa', 4, 'Adm'),
(7, 'receita', 204, 'adiantamentos pontual'),
(7, 'despesa', 5, 'Funcionária'),
(7, 'receita', 205, 'adiantamentos agro lima'),
(7, 'despesa', 6, 'Tarifas bancárias'),
(7, 'receita', 206, 'empréstimos'),
(7, 'despesa', 7, 'Transportes'),
(7, 'receita', 207, 'sicoob'),
(7, 'despesa', 8, 'Seguro'),
(7, 'despesa', 9, 'Documentação'),
(7, 'despesa', 10, 'Impostos'),
(7, 'despesa', 11, 'Pedágios'),
(7, 'despesa', 12, 'Outros'),
(8, 'despesa', 1, 'TARIFAS BANCÁRIAS'),
(8, 'investimento', 101, 'TOP BOI'),
(8, 'receita', 201, 'TOP BOI'),
(8, 'receita', 202, 'TERRAS'),
(8, 'receita', 203, 'TOP VACAS'),
(8, 'receita', 204, 'MÁQUINAS'),
(8, 'receita', 205, 'FÁBRICA DE SAL'),
(8, 'receita', 206, 'CONFINAMENTO'),
(8, 'receita', 207, 'PONTUAL E LIMA AGRO TRANSPORTES'),
(8, 'receita', 208, 'EMPRÉSTIMO RECEBIDO'),
(8, 'receita', 209, 'RECEBEU SICREDI'),
(1, 'despesa', 1, 'impostos'),
(1, 'despesa', 2, 'cartorio/documentacao'),
(1, 'despesa', 3, 'administracao'),
(1, 'despesa', 4, 'banco'),
(1, 'despesa', 5, 'outros'),
(1, 'investimento', 101, 'compra de terra'),
(1, 'investimento', 102, 'emprestimo para TOP BOI'),
(1, 'investimento', 103, 'financiamento pago'),
(1, 'investimento', 104, 'LIMABANK pago/aplicado'),
(1, 'receita', 201, 'venda de terra'),
(1, 'receita', 202, 'recebimento TOP BOI'),
(1, 'receita', 203, 'emprestimo recebido'),
(1, 'receita', 204, 'LIMABANK recebido/resgatado');
